# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_auto_20170711_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='pub_product',
        ),
        migrations.RemoveField(
            model_name='user',
            name='desire',
        ),
        migrations.RemoveField(
            model_name='user',
            name='seller',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='pub_product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='department.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
